channel_targets:
- deepmodeling dev
channel_sources:
  - deepmodeling/label/dev,deepmodeling,https://deepmodeling.njzjz.win,defaults
  - deepmodeling/label/dev,deepmodeling,https://deepmodeling.njzjz.win,defaults,conda-forge

